// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMqcOU_f1JVrLqLevtmXIRq2G3RKDdioM',
    appId: '1:1078370819951:web:73b2572a2d484e1058529a',
    messagingSenderId: '1078370819951',
    projectId: 'vox-cast',
    authDomain: 'vox-cast.firebaseapp.com',
    storageBucket: 'vox-cast.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEHarSs2yBAtfYQiPncZ_yp3OkPDgVca4',
    appId: '1:1078370819951:android:c61c666dd8f8055e58529a',
    messagingSenderId: '1078370819951',
    projectId: 'vox-cast',
    storageBucket: 'vox-cast.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyGnCO7r8Eht4VmQsEFw6PJtZq7mbh5HA',
    appId: '1:1078370819951:ios:8cbafdce4c4fc2e058529a',
    messagingSenderId: '1078370819951',
    projectId: 'vox-cast',
    storageBucket: 'vox-cast.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMqcOU_f1JVrLqLevtmXIRq2G3RKDdioM',
    appId: '1:1078370819951:web:66179eabb338fc5d58529a',
    messagingSenderId: '1078370819951',
    projectId: 'vox-cast',
    authDomain: 'vox-cast.firebaseapp.com',
    storageBucket: 'vox-cast.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyGnCO7r8Eht4VmQsEFw6PJtZq7mbh5HA',
    appId: '1:1078370819951:ios:8cbafdce4c4fc2e058529a',
    messagingSenderId: '1078370819951',
    projectId: 'vox-cast',
    storageBucket: 'vox-cast.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}